function verify_repository()
% VERIFY_REPOSITORY  Check that all project files and required inputs exist.
% This is a repository-integrity check, not a substitute for running MATLAB.

root = fileparts(mfilename('fullpath'));

requiredFiles = { ...
    'script_solve_ode_Arancio.m', ...       % principal manuscript driver
    'run_enei_analysis.m', ...              % elasticity/robustness driver
    'make_figure_R22.m', ...                % Reviewer 2 trajectory figure
    'script_sensitivity_aintro.m', ...
    'script_sensitivity_temperature.m', ...
    'script_sensitivity_humidity.m', ...
    'script_sensitivity_radiation.m', ...
    'script_sensitivity_wind.m', ...
    'apply_parameter_scenario.m', ...
    'build_nominal_parameters.m', ...
    'compute_continuous_endpoints.m', ...
    'compute_indicator.m', ...
    'enei_fT.m', ...
    'enei_rhs.m', ...
    'enei_sensitivity.m', ...
    'export_enei_results.m', ...
    'load_forcing.m', ...
    'load_parameter_intervals.m', ...
    'observed_2002.m', ...
    'preflight_checks.m', ...
    'run_interaction_checks.m', ...
    'run_local_elasticities.m', ...
    'run_range_robustness.m', ...
    'run_range_robustness_B.m', ...
    'set_fT_normalization.m', ...
    'simulate_enei_model.m', ...
    'ENEI_parameter_intervals_updated.csv', ...
    'Arancio_dati_2000_2025.mat'};

missing = strings(0,1);
for k = 1:numel(requiredFiles)
    if ~isfile(fullfile(root, requiredFiles{k}))
        missing(end+1,1) = string(requiredFiles{k}); %#ok<AGROW>
    end
end
if ~isempty(missing)
    error('verify_repository:missingFiles', ...
        'Missing required project files:\n%s', strjoin(missing, newline));
end

% Validate the forcing archive without importing it into the base workspace.
vars = string({whos('-file', fullfile(root,'Arancio_dati_2000_2025.mat')).name});
neededVars = ["Tvec","Hvec","Rvec","Wvec"];
absentVars = neededVars(~ismember(neededVars, vars));
if ~isempty(absentVars)
    error('verify_repository:missingVariables', ...
        'The MAT archive lacks: %s', strjoin(absentVars, ', '));
end
D = load(fullfile(root,'Arancio_dati_2000_2025.mat'), 'Tvec','Hvec','Rvec','Wvec');
channels = {'Tvec','Hvec','Rvec','Wvec'};
n = numel(D.Tvec);
for k = 1:numel(channels)
    x = D.(channels{k});
    if numel(x) ~= n
        error('verify_repository:lengthMismatch', ...
            '%s has a different length from Tvec.', channels{k});
    end
    if any(~isfinite(x(:))) || any(x(:) <= -900)
        error('verify_repository:badForcing', ...
            '%s contains NaN/Inf or an unprocessed fill value.', channels{k});
    end
end

% Validate the authoritative parameter table.
P = readtable(fullfile(root,'ENEI_parameter_intervals_updated.csv'), ...
    'TextType','string','VariableNamingRule','preserve');
requiredCols = ["parameter_id","nominal","lower","upper", ...
    "interval_type","independently_varied"];
absentCols = requiredCols(~ismember(requiredCols, string(P.Properties.VariableNames)));
if ~isempty(absentCols)
    error('verify_repository:missingColumns', ...
        'Parameter CSV lacks columns: %s', strjoin(absentCols, ', '));
end
requiredIds = ["T_min","T_max","T_opt","beta_max","mu_E_min", ...
    "mu_N_min","mu_A_min","gamma_E_max","gamma_N_max","A_intro", ...
    "T_move","alpha_T","alpha_H","delta_T","delta_H","beta_T", ...
    "beta_H","K_W","k_W","alpha_W","c_H","H_m","c_R","R_m"];
ids = strtrim(string(P.parameter_id));
absentIds = requiredIds(~ismember(requiredIds, ids));
if ~isempty(absentIds)
    error('verify_repository:missingParameters', ...
        'Parameter CSV lacks IDs: %s', strjoin(absentIds, ', '));
end

% The main plotting/regression script uses Statistics and Machine Learning Toolbox.
if exist('fitlm','file') ~= 2 || exist('boxplot','file') ~= 2 || exist('prctile','file') ~= 2
    warning('verify_repository:statisticsToolbox', ...
        ['Some manuscript figures/statistics require Statistics and Machine ' ...
         'Learning Toolbox (fitlm, boxplot, prctile).']);
end

fprintf('[verify_repository] All project files and input-data checks passed.\n');
fprintf('[verify_repository] Principal driver: script_solve_ode_Arancio.m\n');
fprintf('[verify_repository] Full supplementary analysis: run_enei_analysis.m\n');
end
